### ISSUE TITLE
Little issue with round corner (Ubuntu/Gnome)

### ISSUE THREAD

**Issue by AnnaTartine** [migueravila/SimplerentFox#24]
Hi, I love the theme (i use bento too !) so thanks.

I just figure out something a little annoying using the theme on ubuntu/gnome. There is a pointy corner showing (with a color problem too) as we can normally see here 

![2021-02-05_20-53](https://user-images.githubusercontent.com/72700208/107083213-99357d00-67f5-11eb-8886-484d752ee59a.png)

The first windows is with SimplerentFox and the second one is default. I cannot figure out how to fix this by my own, how do you thinks is it easy to fix ?

**Comment by MiguelRAvila** [comment]
Hey! @AnnaTartine . 

I got that problems too with some GTK themes and I think that's the problem there. (With the rounded corner ones) Maybe there's  a way to fix it so I'll keep this Issue open. I'll be working on this soon!

**Comment by migueravila** [comment]
Hey @AnnaTartine I've been searching for a solution of this. And I realized that it's caused by the compositor of your system. For example, using a WM with [Picom](https://github.com/ibhagwan/picom) as a compositor, you can get the same result as the screenshots on my readme.

You can also use a GTK theme with no rounded corners and It'll be solved.
