### ISSUE TITLE
Top transparency

### ISSUE THREAD

**Issue by h4pZ** [migueravila/SimplerentFox#32]
Hi,

I'm using your theme and I'm not getting the top bar transparency

![](https://i.imgur.com/mJXmLY2.png)

This is what I have on `userChrome.css` under root
```
:root {
    --srf-color-primary: rgba(17, 17, 17, 0.6);
    --srf-color-selection: #66a6d9;
}
```

I'm not able to get any transparency no matter which `userChrome.css` I used :(

**Comment by migueravila** [comment]
Since some versions ago Firefox has having issues towards transparency. It looks like in Firefox 87 works. But with the new Proton design and major changes. I think that the transparency may be something won't be working so long. I'll close this issue because is more a Firefox "feature". 

I'll keep an eye to see if transparency works again!
